(in-package :finebrush)

(defgeneric draw-brush (brush pixmap x y pressure &rest key-pairs)
  (:documentation "Generic function for drawing brush dub. Should be called by brush-stroke functions."))

(defmethod draw-brush ((brush (eql :simple-square)) pixmap x y pressure &key color)
  (let* ((gc (graphics-context-new pixmap))
	 (x (round (- x (* 10 pressure))))
	 (y (round (- y (* 10 pressure))))
	 (w (round (* 20 pressure)))
	 (h (round (* 20 pressure))))
    (setf (graphics-context-rgb-fg-color gc) color)
    (gdk::draw-rectangle pixmap gc t x y w h)
    (list x y w h)))

(defmethod draw-brush ((brush (eql :simple-round)) pixmap x y pressure &key color)
  (let* ((gc (graphics-context-new pixmap))
	 (x (round (- x (* 10 pressure))))
	 (y (round (- y (* 10 pressure))))
	 (w (round (* 20 pressure)))
	 (h (round (* 20 pressure))))
    (setf (graphics-context-rgb-fg-color gc) color)
    (gdk:draw-arc pixmap gc t x y w h 0 (* 64 360))
    (list x y w h)))
